require Pod::Executable.execute_command('node', ['-p',
  'require.resolve("react-native/scripts/react_native_pods.rb",{paths:[process.argv[1]]},)', __dir__]).strip

platform :ios, '14.0'
prepare_react_native_project!

target 'BreachAlert' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(installer, config[:reactNativePath])
  end
end